apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mi
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None  # If you want headless service (optional)

